version: '3.7'
services:
  trino:
    hostname: trino
    container_name: trino
    image: trinodb/trino:425
    ports:
      - 8080:8080
    volumes:
      - ./docker/trino/conf:/etc/trino:ro
    networks:
      - data-stack

  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: mariadb:10.5.8
    ports:
      - 3306:3306 # MariaDB for Hive Meta Store (HMS)
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: metastore_db
    networks:
      - data-stack

  hive-metastore:
    build: docker/hive-metastore
    hostname: hive-metastore 
    container_name: hive-metastore
    image: hive-metastore:3.1.3
    ports:
      - 9083:9083 # Metastore Thrift
    volumes:
      - ./docker/hive-metastore/conf/metastore-site.xml:/opt/apache-hive-metastore-3.1.3-bin/conf/metastore-site.xml:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      METASTORE_DB_HOSTNAME: mariadb
      METASTORE_TYPE: mysql
    depends_on:
      - mariadb
    networks:
      - data-stack

  minio:
    hostname: minio
    container_name: minio
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER:  $MINIO_USER
      MINIO_ROOT_PASSWORD: $MINIO_USER_PASSWORD
    command: server --console-address ":9001" /data
    networks:
      - data-stack

volumes:
  minio-data:
    driver: local
  
  mariadb-data:
    driver: local

networks:
  data-stack:
    driver: bridge
