version: '3.7'

services:
  trino:
    hostname: trino
    container_name: trino
    image: trinodb/trino:425
    ports:
      - 8080:8080
    volumes:
      - ./docker/trino/conf:/etc/trino:ro
    networks:
      - data-stack

  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: mariadb:10.5.8
    ports:
      - 3306:3306 # MariaDB for Hive Meta Store (HMS)
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: metastore_db
    networks:
      - data-stack

  hive-metastore:
    build: docker/hive-metastore
    hostname: hive-metastore 
    container_name: hive-metastore
    image: hive-metastore:3.1.3
    ports:
      - 9083:9083 # Metastore Thrift
    volumes:
      - ./docker/hive-metastore/conf/metastore-site.xml:/opt/apache-hive-metastore-3.1.3-bin/conf/metastore-site.xml:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      METASTORE_DB_HOSTNAME: mariadb
      METASTORE_TYPE: mysql
    depends_on:
      - mariadb
    networks:
      - data-stack

  minio:
    hostname: minio
    container_name: minio
    image: minio/minio:RELEASE.2023-08-23T10-07-06Z
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER:  $MINIO_USER
      MINIO_ROOT_PASSWORD: $MINIO_USER_PASSWORD
    command: server --console-address ":9001" /data
    networks:
      - data-stack
  
#  rest:
#    image: tabulario/iceberg-rest
#    container_name: iceberg-rest
#    ports:
#      - 8181:8181
#    environment:
#      - AWS_ACCESS_KEY_ID=admin
#      - AWS_SECRET_ACCESS_KEY=password
#      - AWS_REGION=us-east-1
#      - CATALOG_WAREHOUSE=s3://warehouse/
#      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
#      - CATALOG_S3_ENDPOINT=http://minio:9000
#    networks:
#      - data-stack

  spark:
    hostname: spark
    container_name: spark
    image: tabulario/spark-iceberg #official spark+iceberg docker image
    ports:
      - 7077:8080 # Web UI Spark master
      - 8000:8888 # Web UI Jupyter notebook
      - 10000:10000
      - 10001:10001
    volumes:
      - spark-warehouse-data:/home/iceberg/warehouse
      - spark-notebooks-data:/home/iceberg/notebooks/notebooks
    networks:
      - data-stack

volumes:
  minio-data:
    driver: local
  
  mariadb-data:
    driver: local
  
  spark-warehouse-data:
    driver: local
  
  spark-notebooks-data:
    driver: local

networks:
  data-stack:
    driver: bridge
